### ISSUE TITLE
[FEAT] 결과 페이지 이미지 URL 매칭 & CSS 수정

### ISSUE THREAD

**Issue by purin48** [ooutta/find-your-similarity#19]
<h2> [P1] </h2>

**📌 상세 설명**

결과 페이지에 이전 업로드 이미지 띄우기 및 CSS 수정

**📝 체크리스트**

- [ 결과 페이지에 이전 업로드 이미지 띄우기 ]

- [ 이미지 관련 CSS 수정 ]

**Comment by ooutta** [comment]
#20 
개발 완료하였습니다.
